# Generated by Django 5.2.5 on 2025-08-27 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='other_datas',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='victorina',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CodeSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('language', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('success', 'Success'), ('wrong', 'Wrong Answer'), ('runtime', 'Runtime Error'), ('error', 'Error'), ('time_limit_exceeded', 'Time Limit Exceeded'), ('memory_limit_exceeded', 'Memory Limit Exceeded')], max_length=50)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_snippets', to='pages.task')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_snippets', to='pages.user')),
            ],
        ),
    ]
