# Generated by Django 5.2.5 on 2025-08-27 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_lesson_other_datas_lesson_victorina_codesnippet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='other_datas',
            new_name='contents',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='content',
        ),
    ]
