# Generated by Django 5.2.5 on 2025-08-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_other_datas_lesson_contents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, default=[], related_name='enrolled_courses', to='pages.user'),
        ),
    ]
