# Generated by Django 5.2.5 on 2025-08-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='language',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('csharp', 'CSharp')], max_length=50, null=True),
        ),
    ]
