# Generated by Django 5.2.5 on 2025-08-27 17:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_task_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='lesson',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='pages.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='language',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('csharp', 'CSharp'), ('cpp', 'C++')], max_length=50, null=True),
        ),
    ]
