# Generated by Django 5.2.5 on 2025-08-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_chatmessage_lesson_chatmessage_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(blank=True, default='None', max_length=255),
        ),
    ]
