# Generated by Django 5.2.5 on 2025-08-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
