# Generated by Django 5.2.5 on 2025-08-28 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_lesson_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(max_length=50)),
                ('times', models.IntegerField(default=1)),
                ('code_snippet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.codesnippet')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='pages.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
