# Generated by Django 5.2.5 on 2025-08-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_tasksolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='graduates',
            field=models.ManyToManyField(blank=True, default=[], related_name='completed_courses', to='pages.user'),
        ),
    ]
