# Generated by Django 5.2.6 on 2025-09-24 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_lesson_auto_end_access_completedlesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('language_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='inputs',
        ),
        migrations.RemoveField(
            model_name='task',
            name='outputs',
        ),
        migrations.AddField(
            model_name='task',
            name='memory_limit',
            field=models.IntegerField(default=16),
        ),
        migrations.AddField(
            model_name='task',
            name='time_limit',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.language'),
        ),
    ]
