# Generated by Django 5.2.6 on 2025-09-24 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_language_remove_task_inputs_remove_task_outputs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksolution',
            name='language',
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.language'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='expected_output',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input_data',
            field=models.TextField(),
        ),
    ]
